version: 2.1
jobs:
    run_tests:
        docker:
            - image: cimg/node:17.2.0
        steps:
            - checkout
            - run:
                  name: Install npm/yarn dependencies
                  command: yarn
            - run:
                  name: Run unit test
                  command: yarn test
orbs:
    heroku: circleci/heroku@1.2.6

workflows:
    build_test:
        jobs:
            - run_tests
    heroku_deploy:
        jobs:
            - heroku/deploy-via-git
