version: 2.1

jobs:
    build:
        docker:
            - image: cimg/node:17.2.0
        steps:
            - checkout
            - run:
                  name: Install npm/yarn dependencies
                  command: yarn
    test:
        docker:
            - image: cimg/node:17.2.0
        steps:
            - checkout
            - run:
                  name: Install npm/yarn dependencies
                  command: yarn
            - run:
                  name: Run unit test
                  command: yarn test

orbs:
    heroku: circleci/heroku@1.2.6

workflows:
    kinesis_cicd_heroku:
        jobs:
            - build
            - test:
                  requires:
                      - build
            - heroku/deploy-via-git:
                  requires:
                      - test
